<?php


namespace app\modules\quanly\base;


use yii\db\ActiveRecord;
use Yii;

class DanhmucBaseModel extends ActiveRecord
{
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            if($this->hasAttribute('status')){
                $this->status = 1;
            }
            if($this->hasAttribute('created_by')){
                $this->created_by = Yii::$app->user->isGuest ? 0 : Yii::$app->user->id;
            }
            if($this->hasAttribute('created_at')){
                $this->created_at = date('Y-m-d H:i:s');
            }
        } else {
            if($this->hasAttribute('updated_by')){
                $this->updated_by = Yii::$app->user->isGuest ? 0 : Yii::$app->user->id;
            }
            if($this->hasAttribute('updated_at')){
                $this->updated_at = date('Y-m-d H:i:s');
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}